### ISSUE TITLE
Mi Note 10 crash after taking picture (sometimes)

### ISSUE THREAD

**Issue by thiscantbeserious** [eszdman/PhotonCamera#13]
**Describe the bug**
After taking a picture sometimes the latest photon (after tripod detection) crashes. This happens randomly.

**Screenshots**
Settings:

![Screenshot_2020-08-27-09-23-17-229_com eszdman photoncamera](https://user-images.githubusercontent.com/34506214/91410305-00aed000-e847-11ea-8df4-a7ea74a55012.jpg)

**Logs**
````
java.lang.IllegalStateException: Image is already closed
	at android.media.Image.throwISEIfImageIsInvalid(Image.java:72)
	at android.media.ImageReader$SurfaceImage.getPlanes(ImageReader.java:895)
	at com.eszdman.photoncamera.ImageProcessing.ApplyHdrX(ImageProcessing.java:353)
	at com.eszdman.photoncamera.ImageProcessing.Run(ImageProcessing.java:405)
	at com.eszdman.photoncamera.api.ImageSaver.done(ImageSaver.java:41)
	at com.eszdman.photoncamera.api.ImageSaver.Process(ImageSaver.java:177)
	at com.eszdman.photoncamera.api.ImageSaver.lambda$run$0$ImageSaver(ImageSaver.java:79)
	at com.eszdman.photoncamera.api.-$$Lambda$ImageSaver$p8WddnM-eM4NYgwNk6Oi69iNP58.handleMessage(Unknown Source:2)
	at android.os.Handler.dispatchMessage(Handler.java:103)
	at android.os.Looper.loop(Looper.java:224)
	at android.os.HandlerThread.run(HandlerThread.java:67)

````

**Smartphone (please complete the following information):**
 - Device: Xiaomi Mi Note 10
 - OS: MIUI 12.01 on Android 10

**Additional context**

**Comment by eszdman** [comment]
50 frames may be unstable for current camera versions
