### ISSUE TITLE
Crash when I stop recording a video

### ISSUE THREAD

**Issue by D3ZOXY** [eszdman/PhotonCamera#61]
Realme X2 RMX1991 CN. Android 10, Realme UI 1.

FATAL EXCEPTION: main
Process: com.particlesdevs.photoncamera, PID: 13538
java.lang.NullPointerException: Attempt to invoke virtual method 'boolean java.io.File.delete()' on a null object reference
	at com.particlesdevs.photoncamera.capture.CaptureController.stopRecordingVideo(CaptureController.java:1634)
	at com.particlesdevs.photoncamera.capture.CaptureController.VideoEnd(CaptureController.java:1575)
	at com.particlesdevs.photoncamera.ui.camera.CameraFragment$CameraUIController.onClick(CameraFragment.java:1011)
	at com.particlesdevs.photoncamera.ui.camera.CameraFragment$CameraUIViewImpl.lambda$initListeners$1$CameraFragment$CameraUIViewImpl(CameraFragment.java:825)
	at com.particlesdevs.photoncamera.ui.camera.CameraFragment$CameraUIViewImpl$$ExternalSyntheticLambda2.onClick(Unknown Source:2)
	at android.view.View.performClick(View.java:7262)
	at android.view.View.performClickInternal(View.java:7224)
	at android.view.View.access$3800(View.java:824)
	at android.view.View$PerformClick.run(View.java:27726)
	at android.os.Handler.handleCallback(Handler.java:883)
	at android.os.Handler.dispatchMessage(Handler.java:100)
	at android.os.Looper.loop(Looper.java:228)
	at android.app.ActivityThread.main(ActivityThread.java:7820)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:492)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:981)

**Comment by eszdman** [comment]
On what version?

**Comment by D3ZOXY** [comment]
0.8.13049.

**Comment by adam-718** [comment]
It's happening to me as well,
I'm running LineageOS on Asus Zenfone 8.
All other features and multi lenses support are working perfectly.
Maybe because the save path location?
