### ISSUE TITLE
crash when pressing infinite (endless)

### ISSUE THREAD

**Issue by Wjxfi** [eszdman/PhotonCamera#97]
**Describe the bug**

**To Reproduce**
press infinite (endless)

**Expected behavior**

**Screenshots**

**Logs**
```
FATAL EXCEPTION: CameraBackground
Process: com.particlesdevs.photoncamera, PID: 27795
java.lang.NegativeArraySizeException: -1
	at com.particlesdevs.photoncamera.capture.CaptureController.captureStillPicture(CaptureController.java:1552)
	at com.particlesdevs.photoncamera.capture.CaptureController.access$300(CaptureController.java:128)
	at com.particlesdevs.photoncamera.capture.CaptureController$3.process(CaptureController.java:372)
	at com.particlesdevs.photoncamera.capture.CaptureController$3.onCaptureCompleted(CaptureController.java:447)
	at android.hardware.camera2.impl.CameraCaptureSessionImpl$1.lambda$onCaptureCompleted$3$CameraCaptureSessionImpl$1(CameraCaptureSessionImpl.java:701)
	at android.hardware.camera2.impl.CameraCaptureSessionImpl$1$$ExternalSyntheticLambda6.run(Unknown Source:8)
	at android.os.Handler.handleCallback(Handler.java:938)
	at android.os.Handler.dispatchMessage(Handler.java:99)
	at android.os.Looper.loopOnce(Looper.java:210)
	at android.os.Looper.loop(Looper.java:299)
	at android.os.HandlerThread.run(HandlerThread.java:67)
```

```
FATAL EXCEPTION: CameraBackground
Process: com.particlesdevs.photoncamera, PID: 19995
java.lang.NegativeArraySizeException: -1
	at com.particlesdevs.photoncamera.capture.CaptureController.captureStillPicture(CaptureController.java:1552)
	at com.particlesdevs.photoncamera.capture.CaptureController.access$300(CaptureController.java:128)
	at com.particlesdevs.photoncamera.capture.CaptureController$3.process(CaptureController.java:372)
	at com.particlesdevs.photoncamera.capture.CaptureController$3.onCaptureProgressed(CaptureController.java:421)
	at android.hardware.camera2.impl.CameraCaptureSessionImpl$1.lambda$onCaptureProgressed$2$CameraCaptureSessionImpl$1(CameraCaptureSessionImpl.java:687)
	at android.hardware.camera2.impl.CameraCaptureSessionImpl$1$$ExternalSyntheticLambda5.run(Unknown Source:8)
	at android.os.Handler.handleCallback(Handler.java:938)
	at android.os.Handler.dispatchMessage(Handler.java:99)
	at android.os.Looper.loopOnce(Looper.java:210)
	at android.os.Looper.loop(Looper.java:299)
	at android.os.HandlerThread.run(HandlerThread.java:67)
```

**Smartphone (please complete the following information):**
 - Device: vayu (poco x3 pro)
 - OS: miui 13.0.5
 - Version 0.85

**Additional context**

**Comment by eszdman** [comment]
Fixed in 0.87
